### ISSUE TITLE
BUILD.md file in `dev` branch missing dependency?

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminus-server#47]
In the `dev` branch, the `BUILD.md` file doesn't contain the following block compared with the `master` branch:

```
HDT Library

You will also need to install hdt-cpp. You can git clone the source tree from this repository:

git clone https://github.com/rdfhdt/hdt-cpp
```

But installing this dependency seems to still be required. In the `master` branch, the text above should ideally be moved before the instructions to install the SWI-Prolog `hdt` pack otherwise the installation may fail due to missing dependencies (that are listed in the `hdt-cpp` repo readme page). Back to the `dev` branch, if we try to set the admin user password using the command from the `BUILD.md` file:

```
$ utils/db_util -k "my_password_here" -s "my_server_name_here"
```

we will get an error that `db_util` doesn't exist. The command seems to have been renamed to `initialize_database`. But if we try it without first installing `hdt-cpp`from its clone, we get an error that the required `rdf2hdt` command is not installed.

Summarizing:

1. Installing `hdt-cpp` still seems to be required when using the `dev` branch.
2. There's a typo in the `dev` branch `BUILD.md` file: `db_util ` -> `initialize_database `.

I'm hesitant to submit a PR to fix the `BUILD.md` file in the `dev` branch as these issue seem to be caused by work-in-progress...

**Comment by rrooij** [comment]
Hey @pmoura, thanks a lot for spotting this error.

`initialize_database` has been renamed to `db_util` because I want it to be a general configuration utility in the future instead of only a database initialization script. For instance, it must be possible in the future to change your port and the like without having to initialize a whole new database.

I'm not sure whether hdt is still required in dev. I thought it was obsolete since the terminus_store_prolog backend but it might still be used in a place I didn't see.

**Comment by pmoura** [comment]
I re-checked the `dev` branch and I think you're correct. I have been experimenting both `master` and `dev` branches on macOS and Ubuntu and likely I did mixed my findings. Sorry for the noise! So, other than my suggestion to improve the text ordering on the `BUILD.md` file in the `master` branch, the other issues are raised should be invalid. Closing this ticket.
